config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/signin', to: 'sessions#sign_in'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('application#home')
  
 
  resources :users do 
      #resources :tasks, only: [:index]  
      resources :hosts, only: [:index] 
  end 

  resources :hosts  do 
    member do          
      get :completed
    end   
  end 

  resources :hosts  do 
      #resources :tasks, only: [:create, :edit, :update, :destroy ]  do 
      resources :hosts, only: [:create, :edit, :update, :destroy ]  do
        member do          
          patch :complete
        end         
      end
  end

end

app/models/host.rb
class Host < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  belongs_to :user
  has_many :hats

  scope :status, -> { where(status: 'active') }
  scope :recent, -> { order('projects.updated_at DESC') }
  
  def completed?
    !completed_at.blank?
  end 

end

# might try to rework the db this way
# class Host < ActiveRecord::Base

#   has_many :hats
#   has_many :users, through: :hats
# end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
    before_action :authenticate_user
    before_action :set_host, only: [:show, :edit, :update, :destroy, :completed]
  
    def index    
      if current_user.admin
        @users = User.where(admin: false)  
        @hosts = Host.all    
      else 
        @users = User.where(id: current_user.id)
       # @hosts = Host.all.status
      end
    end
  
    def show    
    end
  
    def new
      @host = Host.new
      @hat = Hat.new
    end
  
    def create 
      @host = Host.new(host_params)
      if @host.save
        flash[:notice] = "Successfully created Host."
        redirect_to @host
      else 
        flash[:notice] = "Host not created."
        render :new
      end
    end
  
    def edit
    end
  
    def update     
      if @host.update(host_params)
        flash[:notice] = "Successfully updated host."
        redirect_to @host
      else 
        flash[:notice] = "Un-Successfully updated host."
        render :edit
      end
    end
  
    def destroy     
      if @host.delete
           @hosts = Task.where(:host_id => @host.id)
           
           if @hosts.delete_all
            flash[:notice] = "Successfully deleted this Host !! All hosts for this Host were also deleted !!"
            redirect_to @host
           end
       else
           flash[:notice] = "This Host was not deleted !!"         
           redirect_to hosts_path
       end
    end 
  
    def completed
      @hosts = @host.hosts.completed
      render :"/hosts/completed"
    end 
  
    private
    def set_host
      @host = Host.find_by(id: params[:id])
    end 
  
    def host_params
      params.require(:host).permit(:name, :description, :status)
    end
  
  end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<%= form_for @host do |f| %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>
      
<%# delete the code below znd build radio buttons for hats %>
    <br>
    <%= f.label :status %>
    <%= f.radio_button :status, "active", checked: true %>
    <%= f.label :status_active, "Active" %>

    <%= f.radio_button :status, "deactive" %>
    <%= f.label :status_inactive, "Deactive" %>

    <br>
    <br>
<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/hosts/_forn.html.erb
<%= form_for @host do |f| %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>
      
    <br>
    <%= f.label :description %>
    <%= f.text_field :description %>

    <br>
    <%= f.label :status %>
    <%= f.radio_button :status, "active", checked: true %>
    <%= f.label :status_active, "Active" %>

    <%= f.radio_button :status, "deactive" %>
    <%= f.label :status_inactive, "Deactive" %>

    <br>
    <br>
<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/hosts/edit.html.erb
<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to "Cancel", hosts_path%>
</div>

app/views/hosts/index.html.erb
<h1 class="title">Your Hosts</h1>
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>
<% if @hosts.size == 0
    flash[:notice] = "You have no acitve Hosts...."
  end 
%>
<% @hosts.each do |host| %>
  
  <div class="index_row clearfix">

    <% if host.status == "active" %>
      <h2 class="title">
        <%= link_to host.name, host_path(host) %>  
      </h2>
      
      <h2 class="sub_title">      
        <%= host.description %>         
      </h2>
      
      <br/> 

      <% if current_user.admin %>
      <div class="links">
        <%= link_to "Edit Host", [:edit, host] %>
        <%=   link_to host_path(host), method: :delete, data: { confirm: 'Are you sure you want to delete this Host? All host tasks shall also be deleted.' } do %> 
          
          <i class="fa fa-trash"></i>   
        <% end %>   
      </div>
      <% else %>
        <div class="links">
          <%= link_to "Show Tasks", host_path(host) %>
        </div>
      <% end %>     

    <% else %>
        <h2 class="title">
          <strike><%= link_to host.name, host_path(host) %>  </strike>
        </h2>
              
        <h2 class="sub_title">
          <strike><%= host.description %>  </strike>
        </h2>
        <div class="links">
          <%= link_to "Edit Host", [:edit, host] %>
          <%=   link_to host_path(host), method: :delete, data: { confirm: 'Are you sure you want to delete this Host? All host tasks shall also be deleted.' } do %> 
          
            <i class="fa fa-trash"></i>   
          <% end %>
        </div>
      
  <% end %>

  
  </div>
  
<% end %>

<div class="links">
  <% if current_user.admin %>  
      <p><%= link_to 'New Hosts', new_host_path %></p>  
  <% end %>
</div>

app/views/hosts/new.html.erb
<div class="forms">
    <%= render 'form' %>
</div>

<div class="links">
    <%= link_to "Cancel", hosts_path%>
</div>

app/views/hosts/show.html.erb
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>

<p>
    <h1 class="title">
        <%= @host.name %>
    </h1>    
    <h2 class="title">  
        <%= @host.description %>
    </h2>
</p>
<div class="links">
    <%= link_to "Show hats for Host", completed_host_path(@host) %>
</div>

<div id="wrapper">
    <%= render "tasks/task" %>    
    <% if @host.status == "active" %>
    Create Task:
        <div class="forms">
            <%= render "tasks/form" %>
        </div>
    <% end %>
</div>


<div class="links">
    <% if current_user.admin %>            
        <%= link_to "Edit Host", edit_host_path(@host) %> ||
    <% end %>
     <%= link_to "Back", hosts_path%>
</div>