config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/signin', to: 'sessions#sign_in'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('application#home')
  
 
  resources :users do 
      #resources :tasks, only: [:index]  
      resources :hosts, only: [:index] 
  end 

  resources :hosts  do 
    member do          
      get :completed
    end   
  end 

  resources :hosts  do 
      #resources :tasks, only: [:create, :edit, :update, :destroy ]  do 
      resources :hosts, only: [:create, :edit, :update, :destroy ]  do
        member do          
          patch :complete
        end         
      end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true, length: { minimum: 3 }
  validates :last_name, presence: true, length: { minimum: 2 }

  validates :password, presence: true

  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }


  has_secure_password
  
  has_many :hosts
  has_many :hats, through: :hosts

  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end
  
  def self.create_from_omniauth(auth)
    create! do |user|     
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.first_name = auth["info"]["nickname"]
      user.last_name = auth["info"]["name"]
      # user.email = auth["info"]["email"]
      user.email = user.first_name + "@pgm.com"
      user.password = SecureRandom.hex
    end
  end
  
end
# might try to rework the db this way
# class User < ActiveRecord::Base
#   has_many :hosts
#   has_many :hats, through: :hosts

#    has_secure_password

#    def user
#    end

# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Successfully created User."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:notice] = "Un-Successfully created User."
      render :new
    end

  end

  def show
    @user = User.find_by(id: params[:id])
   # @hosts = @user.hosts.status.uniq

    if !current_user.admin
      if current_user != @user
        redirect_to root_path
      end
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:notice] = "Successfully updated User Profile."
      redirect_to @user
    else
      flash[:notice] = "Un-Successfully updated User Profile."
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :admin )
  end
end

app/views/users/_form.html.erb
 <% if flash[:notice] %>
    <div id="notice">
        <%= flash[:notice] %>
    </div>
<% end %> 

<div class="error_message">
    <% if @user.errors.messages.size != 0 %>
        <% @user.errors.messages.each do |error| %>
            <%= error %><br/>
            <% end %>
    <% end %>
</div>  
  
<%= form_for @user do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>   
     
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>

    <%= f.label :admin, "Check box if you are admin" %>
    <%= f.check_box :admin %>
    <br>
    <br>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<div class="forms">
<h5 class="title">
        Update User Profile
<h5>
    <%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class="forms">
<h5 class="title">
        User Sign Up
<h5>
    <%= render 'form' %>
</div>

app/views/users/show.html.erb
Welcome ! <br/>
<%= @user.first_name %> <%= @user.last_name %>

<p>
    <%= link_to "Edit Profile", edit_user_path(@user) %>
</p>

<% if @user.admin %>
    <p>You are Owner</p>
<% end %>

<h5 class="title">
    <%= link_to "#{@user.first_name}, your list of Hosts", user_hosts_path(@user)%> 
</h5>