config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/signin', to: 'sessions#sign_in'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('application#home')
  
 
  resources :users do 
      #resources :tasks, only: [:index]  
      resources :hosts, only: [:index] 
  end 

  resources :hosts  do 
    member do          
      get :completed
    end   
  end 

  resources :hosts  do 
      #resources :tasks, only: [:create, :edit, :update, :destroy ]  do 
      resources :hosts, only: [:create, :edit, :update, :destroy ]  do
        member do          
          patch :complete
        end         
      end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaygroundApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body>
  <a href="<%= root_url %>"/>Home</a>
    
              <% if current_user %>
                <li><%= link_to "Hello, #{current_user.first_name}!", user_path(current_user) %></li>
                <li><%= link_to "Host Dashboard", hosts_path %></li>
                <li><%= link_to "Log Out", signout_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign Up", new_user_path %></li>
                <li><%= link_to "Sign In", signin_path %></li>
                OR 
               
                <li><%= link_to "Sign in with Github" ,  "/auth/github"  %>    
                </li>
              <% end %>


     
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/layouts/home.html.erb
<h2 class="title">
Fidelity Playground App
</h2>
<h2 class="sub_title"> 
A Westworld Host Creator App
</h2>

<h2 class="sub_title"> 
<img src="https://shatontv.com/wp-content/uploads/2016/10/small-logo-300x300.jpg"/>
</h2>